version: "3"
services:
  node:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/code
    environment:
      - NODE_ENV=production
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
